version: '3'
# We use this docker-compose file for deployment on the GII servers.
# It requires a .env file (mostly, with POSTGRES credentials) at the root of the repo.
services:
    google_pathways_web_app:
      image: brighthive/google_pathways_web_app:latest
      depends_on:
        - postgres_service
      environment:
        - APP_ENV=PRODUCTION
        - SECRET_KEY=${SECRET_KEY}
        - PSQL_USER=${POSTGRES_USER}
        - PSQL_PASSWORD=${POSTGRES_PASSWORD}
        - PSQL_HOSTNAME=postgres_service
        - PSQL_PORT=5432
        - PSQL_DATABASE=pathways
        - BASE_URL=http://0.0.0.0:8000
      ports:
        - "8000:8000"
      volumes:
        - ./google_pathways_web_app:/google-pathways-web-app/google_pathways_web_app
      stdin_open: true
      tty: true
    postgres_service:
      image: postgres:12
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=pathways
      ports:
        - "5432:5432"
