version: '3'

services:
    google_pathways_web_app:
      image: brighthive/google_pathways_web_app:latest
      depends_on:
        - postgres_service
      environment:
        - APP_ENV=PRODUCTION
        - SECRET_KEY=${SECRET_KEY}
      ports:
        - "8000:8000"
      volumes:
        - ./google_pathways_web_app:/google-pathways-web-app/google_pathways_web_app
      stdin_open: true
      tty: true
    postgres_service:
      image: postgres:12
      env_file: .env
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - ./pgdata:/var/lib/postgresql/data/pgdata
      ports:
        - "10031:5432"
    nginx:
      image: nginx:1.15-alpine
      ports:
          - "443:443"
      volumes:
          - ./data/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
          - ./data/nginx:/etc/nginx/conf.d
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      restart: on-failure
